project:
  type: website
  output-dir: docs

website:
  title: "Plot quick reference"
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - href: ggplot2_quick_ref.qmd
        text: ggplot2
      - href: seaborn_quick_ref.qmd
        text: Seaborn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


